# Week 6 Lectorial Exercises

Generate and print 5 integers between 0 and 10 from a numpy random number generator after setting its seed.

In [4]:
# Code block 1
import numpy as np

rseed = 1729
rng = np.random.default_rng(seed = rseed)

# Your code here
print(rng.integers(low=0,high=10,size=5))

[7 0 3 1 7]


Now generate 5 more integers and print them. Now create a random number generator with the same seed as above and generate 5 integers and print them. What do you notice?


In [5]:
# Code block 2
print(rng.integers(low=0,high=10,size=5))

rng2 = np.random.default_rng(seed = rseed)
print(rng2.integers(low=0,high=10,size=5))

[2 0 5 5 8]
[7 0 3 1 7]


Your answer here. The seed decides where in the sequence you start so by printing again we are at a different point in the seed.

Now let us consider the **period** of a random number generator. This is the number of integers it generates until it repeats in a cycle.

Run the following code fragment and write down what you notice. Look at the code in `not_so_random` and explain why you have got your result. Note that the modulus in this random number generator is 13 so we would hope to have a period of 12 (0 is disallowed as usual).

In [10]:
import not_so_random 

nsr = not_so_random.NotSoRandom()
nsr.seed(3) 
print([nsr.random() for _ in  range(26)])

nsr.seed(4)
print([nsr.random() for _ in  range(26)])

nsr.seed(13)
print([nsr.random() for _ in  range(26)])

nsr.seed(14)
print([nsr.random() for _ in  range(26)])

[9, 1, 3, 9, 1, 3, 9, 1, 3, 9, 1, 3, 9, 1, 3, 9, 1, 3, 9, 1, 3, 9, 1, 3, 9, 1]
[12, 10, 4, 12, 10, 4, 12, 10, 4, 12, 10, 4, 12, 10, 4, 12, 10, 4, 12, 10, 4, 12, 10, 4, 12, 10]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[3, 9, 1, 3, 9, 1, 3, 9, 1, 3, 9, 1, 3, 9, 1, 3, 9, 1, 3, 9, 1, 3, 9, 1, 3, 9]


Your answer here. It repeats every 3 digits. In not_so_random the output is just the seed *3 mod 13.

Now try running the code with other seeds. What do you notice?

Your answer here. Still repeats every 3 digits. Setting the seed equal to 13 gives an ouput of only 0s. Setting it equal to 14 is the same as setting it equal to 3 (due to the mod 13?).

Now let us look at generating correlated data from a Gaussian distribution with two variables. This is quite easy using numpy's function `random.multivariate_normal`. (I have used a correlation matrix for the sake of simplicity, but it is not much harder to create a covariance matrix for full generality).

In [20]:
corr = np.array([[1., -0.40],
...                  [-0.40, 1.]])

mean = np.array([2., 0.5])

#Your code here: don't forget to set the seed first
rseed = 123
rng = np.random.default_rng(rseed)
data = np.random.multivariate_normal(mean=mean, cov=corr, size=500)

Now we can check on the result: compute the mean and correlation of the data and explain what you see.

In [21]:
# Your code here
print(np.mean(data),np.corrcoef(data))

1.2847513038895881 [[ 1.  1. -1. ...  1. -1. -1.]
 [ 1.  1. -1. ...  1. -1. -1.]
 [-1. -1.  1. ... -1.  1.  1.]
 ...
 [ 1.  1. -1. ...  1. -1. -1.]
 [-1. -1.  1. ... -1.  1.  1.]
 [-1. -1.  1. ... -1.  1.  1.]]


Your answer here.